version: '3'

services:
  interlocking_bridge:
      platform: linux/amd64
      image: ghcr.io/eulynx-live/rasta-protocol/rasta_grpc_bridge_udp:main
      command:
        - /var/rasta.cfg
        - 0.0.0.0:4242
        - "172.24.0.3"
        - "9998"
        - "172.24.0.3"
        - "9999"
        - "97"
        - "96"
        - "172.24.0.1:50001"
      volumes:
        - ./config/rasta_interlocking.cfg:/var/rasta.cfg:ro
      networks:
        bridge_net:
          ipv4_address: 172.24.0.2

  oc_bridge:
      platform: linux/amd64
      depends_on: [interlocking_bridge]
      image: ghcr.io/eulynx-live/rasta-protocol/rasta_grpc_bridge_udp:main
      command:
        - /var/rasta.cfg
        - 0.0.0.0:50002
        - "172.24.0.2"
        - "8888"
        - "172.24.0.2"
        - "8889"
        - "96"
        - "97"
      ports:
        - 50002:50002
      volumes:
        - ./config/rasta_oc.cfg:/var/rasta.cfg:ro
      networks:
        bridge_net:
          ipv4_address: 172.24.0.3

networks:
  bridge_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.24.0.0/16
         gateway: 172.24.0.1