number_of_pins=3
pins_output=["O_1", "O_3", "O_5"]
pins_output_backup=["O_2", "O_4", "O_6"]
pins_input=["I_1", "I_2", "I_3"]
day_night_pin= "O_7"
# sci signals supported:
# - Hp0,
# - Hp0PlusSh1
# - Hp0WithDrivingIndicator
# - Ks1
# - Ks2
# - Ks1Flashing
# - Ks1FlashingWithAdditionalLight
# - Ks2WithAdditionalLight
# - Sh1
# - IdLight
# - Hp0Hv
# - Hp1
# - Hp2
# - Vr0
# - Vr1
# - Vr2
# - Off
signals={"Off"=[0,0,0], "Ks1"=[1,0,0], "Ks2"=[0,1,0]}
